#!/bin/sh
#
# /etc/rc: system boot script
#

echo "The system is coming up.  Please wait."

# Set the hostname
hostname crux

# Mount proc pseudo-fs and sysfs
/bin/mount -t proc none /proc
/bin/mount -t sysfs none /sys

# Start udev
/sbin/start_udev

# Mount filesystems
/bin/mount -n -a &> /dev/null

# Create /tmp/var
/bin/mkdir /tmp/var
/bin/chmod 0755 /tmp/var
/bin/mkdir /var/lock /var/log /var/run /var/tmp
/bin/touch /var/run/utmp

# Create /run/cryptsetup for cryptsetup
/bin/mkdir /run/cryptsetup

# Start log daemons
/usr/sbin/syslogd

# Setup network
/sbin/ifconfig lo 127.0.0.1

# mount efivarfs if possible
if [ -d /sys/firmware/efi/efivars ]; then
	/bin/mount /sys/firmware/efi/efivars &> /dev/null
fi

# End of file
